FROM node:8.1.3-alpine
MAINTAINER Todsaporn Banjerdkit <katopz@gmail.com>

# Use production environments
ENV NODE_ENV production

# Create app direactory
RUN mkdir -p /usr/app
WORKDIR /usr/app

# Install app dependencies
COPY package.json /usr/app/package.json
RUN npm install --production

# Bundle app source
COPY . /usr/app

EXPOSE 3000
CMD ["npm", "run", "_serve"]