// Before verify
exports.USER_SIGNUP_WITH_EMAIL = '0'
exports.USER_SIGNUP_WITH_FACEBOOK = '1'
exports.USER_SIGNUP_WITH_FACEBOOK_AND_EMAIL = '2'

// After verify
exports.USER_VERIFIED_BY_EMAIL = '100'
exports.USER_VERIFIED_BY_FACEBOOK = '101'
exports.USER_VERIFIED_BY_FACEBOOK_AND_EMAIL = '102'
