// Before verify
exports.USER_SIGNUP_WITH_EMAIL = '0'
exports.USER_SIGNUP_WITH_FACEBOOK_VERIFIED_EMAIL = '1'
exports.USER_SIGNUP_WITH_FACEBOOK_UNVERIFIED_EMAIL = '2'
exports.USER_SIGNUP_WITH_FACEBOOK_CHALLENGED_EMAIL = '3'

// After verify
exports.USER_HAS_BEEN_VERIFIED_BY_EMAIL = '100'
exports.USER_HAS_BEEN_VERIFIED_BY_FACEBOOK = '101'
exports.USER_HAS_BEEN_VERIFIED_BY_FACEBOOK_EMAIL = '103'
