version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule update --init --recursive
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "graphql/content/package.json" }}
      #     - v1-dependencies-
      # - run: npm install
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "graphql/content/package.json" }}
      # - run: npm run test:once
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  deploy-local:
    docker:
      - image: node:8.9.1
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: apt-get update -y
      - run: apt-get install -y rsync
      - run: mkdir dist
      - run: tar --exclude='./dist/artifact.tar' --exclude='.git' --exclude='.env' --exclude='./graphql/content/node_modules' --exclude='./graphql/content/lib/validator/node_modules' --exclude='./node_modules' --exclude='./.vscode' -czf ./dist/artifact.tar ./
      - run: rsync -e 'ssh -o "StrictHostKeyChecking=no"' -avz ./dist/artifact.tar $DEPLOY_TARGET:/opt/jamplay-nap.tar
      - run: ssh -o "StrictHostKeyChecking=no" -t $DEPLOY_TARGET 'cd /opt && mkdir -p jamplay-nap && ls && tar -xvf jamplay-nap.tar -C /opt/jamplay-nap && cd jamplay-nap && npm install --unsafe-perm'

workflows:
  version: 2
  buld-and-deploy:
    jobs:
      - test
      - deploy-local:
          requires:
            - test
          filters:
            branches:
              only: develop
