steps:
- name: gcr.io/jamplay-prod/git
  args: ['submodule', 'update', '--recursive', '--init']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA','-f', 'jamplay.Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest"]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment', '${_DEPLOYMENT_NAME}', 'nap=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA', "--namespace=staging"]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'