steps:
- name: gcr.io/jamplay-prod/git
  args: ['submodule', 'update', '--recursive', '--init']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME', '-f', 'jamplay.Dockerfile', '.']
images: ['gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME']
